services:
    mongodb:
        image: mongo:latest
        container_name: mernChallengeMongo
        hostname: mongodb
        volumes:
            - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
            - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
            - ./.docker/mongodb/data/db/:/data/db/
            - ./.docker/mongodb/data/log/:/var/log/mongodb/
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin 
            MONGODB_USER: admin
            MONGODB_PASS: admin
        ports:
            - "27017:27017"
networks:
  mongo-compose-network:
    driver: bridge